### ISSUE TITLE
no `list` command

### ISSUE THREAD

**Issue by ljharb** [oftn-oswg/oftn-bot#5]
There isn't currently any way to list all factoids. something like `list` would be ideal to list all currently known factoids.

**Comment by ljharb** [comment]
@dsamarin why close this? it's still a valid feature request.

**Comment by brigand** [comment]
It could create a gist with all of the factoids.

**Comment by ljharb** [comment]
I'd rather it print them out than dump an easily copyable list - that makes it easier to abuse.

**Comment by brigand** [comment]
What's the use case for this?

**Comment by dsamarin** [comment]
Might I suggest to @inimino a symlink to ecmabot-factoids.json on his server?

**Comment by ljharb** [comment]
The point here is a generic thing for oftn-bot, not just for ecmabot. And no, I don't want people getting that entire list, because then they will troll through the factoids, and delete, edit, etc.

**Comment by brigand** [comment]
If you're worried about that, then not listing them at all seems safest. But again, what's the use case for this? Why would I ever use the command if I wasn't looking to do evil things. It's not exactly user friendly.

**Comment by ljharb** [comment]
thats true. The use case is to know if something already exists so it can be improved, before adding a redundant new one.

Perhaps it's better not to have this feature, though, since any form of browsing makes abuse likely, absent a permissions system.

**Comment by brigand** [comment]
Then perhaps we could improve the search feature. If we only allow it in private messages then it could output multiple lines, one for each matching factoid including the contents, limited to say 10.

**Comment by ljharb** [comment]
The need for browsing is when there's nothing searchable, because I don't know the exact wording someone used in their factoid.

**Comment by hagb4rd** [comment]
as by now implemented already in babelboot (oftnbot too? irrelevant tho), any output beyond limit is pasted to gist (or whereever). right now the maxout is btw set annoyingly low when printing errors. so you like always have to open the paste to figure out even the error message. 

pasting to gist would also allow to use markdown templates and/or prettyfiers in dependency of the output. talking about Errors, babelboot and gist: the template for errors would be such an example. using correct formatting that ^ marker is allowed to be useful. 

but listing factoids doesn't seem very ambitious at all. how about making a js vm providing 
providing bot l e a r n commands? could be implemented similarily to node's repl [defineCommand ](https://nodejs.org/api/repl.html#repl_replserver_definecommand_keyword_cmd) .. and i mean as simple as above all. maybe generally parsing the text into arguments like via minimist or commander tho. 

greetz, hag

**Comment by ljharb** [comment]
I don't think we want the bot to be fully dynamically configurable - that adds a bunch of security risks. The `learn` command is sufficient for now.
