### ISSUE TITLE
fetch title and some stats from youtube

### ISSUE THREAD

**Issue by sillyslux** [oftn-oswg/oftn-bot#63]
people paste youtube links, and it's just annoying to run into pokemon and dragonball vids.
please make the bot load the title and some statistics and paste it to the channel.
e.g. on #ubuntu-hr it looks like this:
`<user> https://www.youtube.com/watch?v=gSrnXgAmK8k`
`<bot> ^ YouTube :: All of our data is GONE! :: Duration: 22:58 :: Views: 2,343,987 uploaded by LinusTechTips :: 89,467 likes :: 1,530 dislikes :: 0 favorites`

**Comment by eligrey** [comment]
Are you a mod in the channel? I would definitely ask one to handle the user if you aren't. Other than that you could look into disabling the YouTube feature. I think it's pretty useful though.

**Comment by ljharb** [comment]
oftn-bot seems to pretty intentionally not respond to random triggers, only a short, finite list of explicit triggers.

Adding something like `!youtube $link` might be nice, but responding to any pasted youtube link seems extreme.

**Comment by inimino** [comment]
Agreed that parsing random links is not the way to handle people posting off-topic content. Maybe ask them politely not to do that instead.

Extra botspam is not always appreciated in the channel either. That is indeed why we only respond to explicit triggers.

**Comment by sillyslux** [comment]
ups
